[build]
  publish = "public/"
  command = "npm run build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18.12.1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200